package com.qilin.cms.model;

import java.util.Date;

public class Feedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_feed_back.id
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_feed_back.content
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_feed_back.date
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_feed_back.muid
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    private Long muid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_feed_back.phone
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_feed_back.id
     *
     * @return the value of system_feed_back.id
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_feed_back.id
     *
     * @param id the value for system_feed_back.id
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_feed_back.content
     *
     * @return the value of system_feed_back.content
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_feed_back.content
     *
     * @param content the value for system_feed_back.content
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_feed_back.date
     *
     * @return the value of system_feed_back.date
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_feed_back.date
     *
     * @param date the value for system_feed_back.date
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_feed_back.muid
     *
     * @return the value of system_feed_back.muid
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    public Long getMuid() {
        return muid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_feed_back.muid
     *
     * @param muid the value for system_feed_back.muid
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    public void setMuid(Long muid) {
        this.muid = muid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_feed_back.phone
     *
     * @return the value of system_feed_back.phone
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_feed_back.phone
     *
     * @param phone the value for system_feed_back.phone
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}