package com.qilin.cms.dao.mapper;

import com.qilin.cms.model.Feedback;
import com.qilin.cms.model.FeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_feed_back
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    int countByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_feed_back
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    int deleteByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_feed_back
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_feed_back
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    int insert(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_feed_back
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    int insertSelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_feed_back
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    List<Feedback> selectByExample(FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_feed_back
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    Feedback selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_feed_back
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") Feedback record, @Param("example") FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_feed_back
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    int updateByExample(@Param("record") Feedback record, @Param("example") FeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_feed_back
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    int updateByPrimaryKeySelective(Feedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_feed_back
     *
     * @mbggenerated Tue Jul 26 12:15:24 CST 2016
     */
    int updateByPrimaryKey(Feedback record);
}