package com.qilin.cms.model;

public class User{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_list.id
     *
     * @mbggenerated Mon Jul 25 11:25:10 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_list.passwd
     *
     * @mbggenerated Mon Jul 25 11:25:10 CST 2016
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_list.username
     *
     * @mbggenerated Mon Jul 25 11:25:10 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_user_list.role
     *
     * @mbggenerated Mon Jul 25 11:25:10 CST 2016
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_list.id
     *
     * @return the value of admin_user_list.id
     *
     * @mbggenerated Mon Jul 25 11:25:10 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_list.id
     *
     * @param id the value for admin_user_list.id
     *
     * @mbggenerated Mon Jul 25 11:25:10 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_list.passwd
     *
     * @return the value of admin_user_list.passwd
     *
     * @mbggenerated Mon Jul 25 11:25:10 CST 2016
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_list.passwd
     *
     * @param passwd the value for admin_user_list.passwd
     *
     * @mbggenerated Mon Jul 25 11:25:10 CST 2016
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_list.username
     *
     * @return the value of admin_user_list.username
     *
     * @mbggenerated Mon Jul 25 11:25:10 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_list.username
     *
     * @param username the value for admin_user_list.username
     *
     * @mbggenerated Mon Jul 25 11:25:10 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_user_list.role
     *
     * @return the value of admin_user_list.role
     *
     * @mbggenerated Mon Jul 25 11:25:10 CST 2016
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_user_list.role
     *
     * @param role the value for admin_user_list.role
     *
     * @mbggenerated Mon Jul 25 11:25:10 CST 2016
     */
    public void setRole(String role) {
        this.role = role;
    }
}